name: 'Setup Environment'
description: 'Setup shared environment variables'
runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
        echo "PROJECT_PATH=./src/LDJam58" >> $GITHUB_ENV
        echo "ITCH_IO_PROJECT=enigmadragons/gallery-genius" >> $GITHUB_ENV

# You must also set the following secrets in your repository settings:
# - secrets.UNITY_EMAIL
# - secrets.UNITY_PASSWORD 
# - secrets.UNITY_LICENSE or secrets.UNITY_SERIAL
#   see: https://game.ci/docs/github/activation#personal-license
#   and  https://game.ci/docs/github/activation#professional-license
#
# - secrets.ITCH_IO_API_KEY
#   see: https://itch.io/docs/itchio/cli/#getting-an-api-key
# Note the above "ITCH_IO_PROJECT" is formed from the user/project-name

# Oh, hey, you are are probably wondering why I don't use GitHub's Action Variables?
# 
# * They are not in source control, and just create more places to we have to manually
#   manage things: Did we sprll is right? Do I have permission to edit it? etc.
# * There are some variables (like SHORT_SHA) that are not have to be computer anyway,
#   so why not just set all the "global" things in one place.
# * Settings don't show up in a code search, making them harder to validate and maintain.
#   "Is this the project with the extra options?" "Did I miss one?" etc.
