# https://game.ci/docs/github/builder#complete-example
name: Cache Clean Test

on: 
  workflow_dispatch:
    inputs:
      # Add a boolean input to decide whether to Free the Android Disk Space
      clear_android_cache:
        description: 'Clear the Android Disk Space before building'
        required: true
        type: boolean
        default: false
      clear_haskell_disk_space:
        description: 'Clear the Haskell Disk Space before building'
        required: true
        type: boolean
        default: false
      clear_docker_images_disk_space:
        description: 'Clear the Docker Images Disk Space before building'
        required: true
        type: boolean
        default: false
      clear_tool_cache_disk_space:
        description: 'Clear the Tool Cache Disk Space before building'
        required: true
        type: boolean
        default: false
      clear_dotnet_disk_space:
        description: 'Clear the Dotnet Disk Space before building'
        required: true
        type: boolean
        default: false
      clear_large_packages_disk_space:    
        description: 'Clear the Large Packages Disk Space before building'
        required: true
        type: boolean
        default: false
      clear_swap_storage_disk_space:
        description: 'Clear the Swap Storage Disk Space before building'
        required: true
        type: boolean
        default: false

env:
  PROJECT_PATH: './src/LDJam58'

jobs:
  diskCleanTest:
    name: Cache Clean Test
    runs-on: ubuntu-latest

    steps:
      - name: Log configuration
        run: |
          echo "Cache Clean Configuration:"
          echo "Android: ${{ inputs.clear_android_cache }}"
          echo "Haskell: ${{ inputs.clear_haskell_disk_space }}"
          echo "Docker: ${{ inputs.clear_docker_images_disk_space }}"
          echo "Tool Cache: ${{ inputs.clear_tool_cache_disk_space }}"
          echo "Dotnet: ${{ inputs.clear_dotnet_disk_space }}"
          echo "Large Packages: ${{ inputs.clear_large_packages_disk_space }}"
          echo "Swap Storage: ${{ inputs.clear_swap_storage_disk_space }}"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: ./.github/actions/setup-environment

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: ${{ inputs.clear_android_cache }}
          haskell: ${{ inputs.clear_haskell_disk_space }}
          docker-images: ${{ inputs.clear_docker_images_disk_space }}
          tool-cache: ${{ inputs.clear_tool_cache_disk_space }}
          dotnet: ${{ inputs.clear_dotnet_disk_space }}
          large-packages: ${{ inputs.clear_large_packages_disk_space }}
          swap-storage: ${{ inputs.clear_swap_storage_disk_space }}
