name: Deploy

run-name: Deploy '${{ inputs.tag }}' requested by ${{ github.event.client_payload.pusher || github.actor }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to be deployed.
        required: true
      channel:
        description: The channel to be deployed.
        required: true
        type: choice
        options:
          - StandaloneOSX
          # - StandaloneWindows
          - StandaloneWindows64
          # - StandaloneLinux64
          # - iOS
          # - Android
          - WebGL

env:
  RELEASE_TAG: ${{ inputs.tag }}
  CHANNEL: ${{ inputs.channel }}

jobs:
  exports:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Upload ${{ matrix.preset }} to itch.io project
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/${{ matrix.preset }}
          project: ${{ env.ITCH_IO_PROJECT }}
          channel: ${{ env.CHANNEL }}
          version: ${{ env.RELEASE_TAG }}
          api-key: ${{ secrets.ITCH_IO_API_KEY }}
