name: Deploy To Itch.io

run-name: Deploy '${{ inputs.tag }}' ${{ inputs.channel }} to Itch.io requested by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to be deployed (e.g., gallery-genius-v19-WebGL)
        required: true
        default: latest
      channel:
        description: The platform channel to be deployed (ignored if tag is provided)
        required: true
        type: choice
        options:
          - WebGL
          - StandaloneWindows64
          - StandaloneOSX
          # - StandaloneWindows
          # - StandaloneLinux64
          # - iOS
          # - Android

env:
  RELEASE_TAG: ${{ inputs.tag }}
  CHANNEL: ${{ inputs.channel }}

jobs:
  deploy:
    name: Deploy to itch.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-environment

      - name: Resolve tag
        id: resolve-tag
        run: |
          if [ "${{ inputs.tag }}" = "latest" ]; then
            LATEST_TAG=$(git tag --sort=-version:refname | grep "\-${{ inputs.channel }}$" | head -n 1)
            if [ -z "$LATEST_TAG" ]; then
              echo "::error::No build tags found ending with '-${{ inputs.channel }}'"
              exit 1
            fi
            echo "ARTIFACT_NAME=$LATEST_TAG" >> $GITHUB_ENV
            echo "Using latest build tag for ${{ inputs.channel }}: $LATEST_TAG"
          else
            # User entered the full tag like "gallery-genius-v19-WebGL"
            echo "ARTIFACT_NAME=${{ inputs.tag }}" >> $GITHUB_ENV
            echo "Using specified tag: ${{ inputs.tag }}"
          fi

      # This action is known to be better at finding artifacts across workflow runs
      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build/${{ inputs.channel }}
          workflow: build.yaml
          workflow_conclusion: success

      - name: Upload to itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/${{ inputs.channel }}
          project: ${{ env.ITCH_IO_USER }}/${{ env.PROJECT_NAME }}
          channel: ${{ inputs.channel }}
          version: ${{ env.ARTIFACT_NAME }}
          api-key: ${{ secrets.ITCH_IO_API_KEY }}
